name: Collect Release URLs

on:
  schedule:
    - cron: '0 0,12 * * *'  # Run at 00:00 and 12:00 UTC daily
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  collect_urls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run collect_github_release_urls.py
        env:
          REVERSE_PROXY_URL: ${{ secrets.REVERSE_PROXY_URL }}
        run: |
          python collect_github_release_urls.py

      - name: Run update_alist_urltree.py
        env:
          ALIST_URL: ${{ secrets.ALIST_URL }}
          ALIST_USERNAME: ${{ secrets.ALIST_USERNAME }}
          ALIST_PASSWORD: ${{ secrets.ALIST_PASSWORD }}
          ALIST_DRIVER_PATH: ${{ secrets.ALIST_DRIVER_PATH }}
          ALIST_DRIVER_ID: ${{ secrets.ALIST_DRIVER_ID }}
        run: |
          python update_alist_urltree.py